### ISSUE TITLE
[Bug Report] Crashed when pressed key 

### ISSUE THREAD

**Issue by SoulAttacker** [QuanhuZeYu/Qz-Miner#19]
## Bug Description
程式在按下连锁按键后崩溃，没有修改任何配置信息。mod版本:0.10.4
Report link: https://mclo.gs/hbFPl6O

### Highlight
```
FATAL ERROR in native method: Thread[#1,Client thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL30C.nglGenVertexArrays(Native Method)
	at org.lwjgl.opengl.GL30C.glGenVertexArrays(GL30C.java:2420)
	at org.lwjgl.opengl.GL30.glGenVertexArrays(GL30.java:2346)
	at org.lwjglx.opengl.GL30.glGenVertexArrays(GL30.java:396)
	at club.heiqi.qz_miner.client.renderSelect.RenderSelect.initVao(RenderSelect.java:194)
	at club.heiqi.qz_miner.client.renderSelect.RenderSelect.renderBlock(RenderSelect.java:244)
	at club.heiqi.qz_miner.client.renderSelect.RenderSelect.enduringAddCacheAndRender(RenderSelect.java:171)
	at club.heiqi.qz_miner.client.renderSelect.RenderSelect.onDrawBlockHighlightEvent(RenderSelect.java:134)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_987_RenderSelect_onDrawBlockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6110)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.invoke.LambdaForm$DMH/0x000000d00100c000.invokeStatic(java.base@21.0.2/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x000000d001113400.invoke(java.base@21.0.2/LambdaForm$MH)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@21.0.2/Invokers$Holder)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@21.0.2/DirectMethodHandleAccessor.java:154)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@21.0.2/DirectMethodHandleAccessor.java:103)
	at java.lang.reflect.Method.invoke(java.base@21.0.2/Method.java:580)
	at net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:60)
	at java.lang.invoke.LambdaForm$DMH/0x000000d00100c000.invokeStatic(java.base@21.0.2/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x000000d001113400.invoke(java.base@21.0.2/LambdaForm$MH)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@21.0.2/Invokers$Holder)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@21.0.2/DirectMethodHandleAccessor.java:154)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@21.0.2/DirectMethodHandleAccessor.java:103)
	at java.lang.reflect.Method.invoke(java.base@21.0.2/Method.java:580)
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207)
	at java.lang.invoke.LambdaForm$DMH/0x000000d00100c400.invokeStaticInit(java.base@21.0.2/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x000000d00100cc00.invokeExact_MT(java.base@21.0.2/LambdaForm$MH)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

## Other
感谢您做出的贡献，如果需要更多信息，请不要介意继续留言。

**Comment by QuanhuZeYu** [comment]
新版本有配置项可以关掉渲染框，v1.11.0尝试关闭渲染框再试试有没有报错

**Comment by SoulAttacker** [comment]
> 新版本有配置项可以关掉渲染框，v1.11.0尝试关闭渲染框再试试有没有报错

fixed after disable rendering
